# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnSAFE_Bank' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.7'
pod 'KeychainAccess'
pod 'CryptoSwift'
pod 'lottie-ios'
  # Pods for damnVIA

end
